### ISSUE TITLE
Preview image in the readme is misleading

### ISSUE THREAD

**Issue by MilkAndBanana01** [Multirious/gd-advanced-inspector-exporter#1]
I was wondering why it wasn't working when I added your example in the readme using:

e.export_category('')
e.export_default('',TYPE_SOMETHING)

It turns out that you didn't need the export_ in the phrase. You might wanna update it to make it less confusing for other users.
Asides that, great work on the addon <3
Hopefully I can see some kind of default value support in the future :D

**Comment by Multirious** [comment]
Oh I'm absolutely forgot to update the preview image. Thanks for issuing!
And sorry for the late reply. I'm working on another another project and github notifies me absolutely nothing from this repos.

**Comment by Multirious** [comment]
Updated readme

**Comment by Multirious** [comment]
> default value support

Could you clarify on what this do?

And if you're curious on why did I open and close this issue so many times. Yes, I don't know how to use github.
This is literally my first issue and I'm panicking.
